!question{4}{
When handling an exception using a try {} catch (...) {} finally {} block, the statements in the finally block will always be executed regardless of the code in the try or catch.
}
